basePath: /
consumes:
- application/json
definitions:
  CustomError:
    description: CustomError custom error
    properties:
      errors:
        description: errors
        items:
          $ref: '#/definitions/ErrorFeild'
        type: array
        x-go-name: Errors
      statusCode:
        description: status code
        format: int64
        type: integer
        x-go-name: StatusCode
    type: object
    x-go-package: github.com/Bilal-Z/go-ms-tutorial-nj/product-api/sdk/models
  ErrorFeild:
    description: ErrorFeild error feild
    properties:
      feild:
        description: feild
        type: string
        x-go-name: Feild
      message:
        description: message
        type: string
        x-go-name: Message
    type: object
    x-go-package: github.com/Bilal-Z/go-ms-tutorial-nj/product-api/sdk/models
  Product:
    description: Product Product defines the structure for an API product
    properties:
      description:
        description: the description for this poduct
        maxLength: 10000
        type: string
        x-go-name: Description
      id:
        description: the id for the product
        format: int64
        minimum: 1
        type: integer
        x-go-name: ID
      name:
        description: the name for this poduct
        maxLength: 255
        type: string
        x-go-name: Name
      price:
        description: the price for the product
        format: float
        minimum: 0.01
        type: number
        x-go-name: Price
      sku:
        description: the SKU for the product
        pattern: '[a-z]+-[a-z]+-[a-z]+'
        type: string
        x-go-name: SKU
    required:
    - name
    - price
    - sku
    type: object
    x-go-package: github.com/Bilal-Z/go-ms-tutorial-nj/product-api/sdk/models
info:
  description: Documentation for Product API
  title: Product API
  version: 0.0.1
paths:
  /products:
    get:
      description: Returns a list of products
      operationId: listProducts
      responses:
        "200":
          $ref: '#/responses/productsResponse'
        "500":
          $ref: '#/responses/errorResponse'
      tags:
      - products
    post:
      description: Create a new product
      operationId: createProduct
      parameters:
      - description: |-
          Product data structure to Update or Create.
          Note: the id field is ignored by update and create operations
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Product'
      responses:
        "201":
          $ref: '#/responses/productResponse'
        "400":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      tags:
      - products
  /products/{id}:
    put:
      description: update a specific product
      operationId: updateProduct
      parameters:
      - description: |-
          Product data structure to Update or Create.
          Note: the id field is ignored by update and create operations
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Product'
      - description: The id of the product for which the operation relates
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/productResponse'
        "400":
          $ref: '#/responses/errorResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      tags:
      - products
produces:
- application/json
- application/text
responses:
  errorResponse:
    description: custom json error
    schema:
      $ref: '#/definitions/CustomError'
  productResponse:
    description: A single product
    schema:
      $ref: '#/definitions/Product'
  productsResponse:
    description: A list of products
    schema:
      items:
        $ref: '#/definitions/Product'
      type: array
schemes:
- http
swagger: "2.0"
